# Generated by Django 4.2.1 on 2023-06-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("election", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="votes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
