# Generated by Django 4.2.1 on 2023-05-15 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("logo", models.ImageField(blank=True, null=True, upload_to="clubs")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("on_election", "On election"),
                            ("inactive", "Inactive"),
                            ("winner", "Winner"),
                        ],
                        default="inactive",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.IntegerField()),
                ("group_number", models.CharField(max_length=10)),
                ("faculty", models.CharField(max_length=6)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("patronymic", models.CharField(max_length=30)),
                ("student_credit", models.IntegerField()),
                ("course", models.IntegerField()),
                (
                    "training_form",
                    models.CharField(
                        choices=[
                            ("full_time", "Очная"),
                            ("distance", "Заочная"),
                            ("full_time_and_distance", "Очно-заочная"),
                        ],
                        default="full_time",
                        max_length=25,
                    ),
                ),
                ("age", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("choise", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Winner",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("season", models.IntegerField()),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.club"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Selection",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("club_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.Club")),
                ("votes", models.IntegerField()),
            ],
        ),
    ]
