# Generated by Django 4.2.1 on 2023-05-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selection",
            name="votes",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="student",
            name="age",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_credit",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="winner",
            name="season",
            field=models.PositiveIntegerField(),
        ),
    ]
